#!/bin/sh

dir=$(dirname "$0")
grammar="${dir}/math.jj"
cc="${dir}/javacc-7.0.5.jar"
out="${dir}/../src/main/java/com/mesut/math/parser2"

java -cp "${cc}" javacc -OUTPUT_DIRECTORY="${out}" -FORCE_LA_CHECK=true "${grammar}"
